### ISSUE TITLE
Crawler don't stop if redis is not available

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#150]
As the containers might not start at the same time/in the right order, might restarts, etc.: the crawler will continue without using redis.

**Comment by etienne-napoleone** [comment]
No, the opposite! 
For now, when the crawler start, if redis is not up, it will continue without it and ignore redis. It should stop instead

**Comment by thanhson1085** [comment]
Perhaps there is no jobs, so the crawler does ping Redis.

I tested on my side. Crawler stoped
```
Redis Connection Error !!! { AbortError: Redis connection lost and command aborted. It might have been proces
sed.
    at RedisClient.flush_and_error (/home/vagrant/projects/tomomaster/node_modules/redis/index.js:357:23)
    at RedisClient.connection_gone (/home/vagrant/projects/tomomaster/node_modules/redis/index.js:659:14)    at Socket.<anonymous> (/home/vagrant/projects/tomomaster/node_modules/redis/index.js:293:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'UNCERTAIN_STATE',
  command: 'BLPOP',
  args: [ 'tomomaster:reward:jobs', 0 ] }
``

**Comment by etienne-napoleone** [comment]
Ah ok, cool my bad then. maybe I got confused because of docker service logs who combine all the containers of a service logs! :)
