### ISSUE TITLE
Only shows a white screen when not connected to the Internet

### ISSUE THREAD

**Issue by probonopd** [tomochain/tomomaster#347]
Only shows a white screen when not connected to the Internet:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/d71c9e0b169f431ea2212a0ef5a827068fc292f7/database/HermesMessenger/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/921

**Comment by thanhson1085** [comment]
Are you running desktop version? 
Window, Mac or Ubuntu?

**Comment by probonopd** [comment]
AppImage on Ubuntu without an Internet connection.

**Comment by thanhson1085** [comment]
Yep, thank you for the report

**Comment by probonopd** [comment]
```
Uncaught Exception:
Error: Cannot find module 'is-online'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-10303/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10303/resources/app.asar/elect.js:2:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-10303/resources/app.asar/elect.js:54:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
```
